#!/bin/bash

#gcc -Wall -O3 -fno-tree-vectorize -I/usr/local/include -c src/main.c -o src/main.o
#gcc -O3 -fno-tree-vectorize -L/usr/local/lib -lgsl -lgslcblas src/main.o

# Number of iterations to run (changes both python and C code)
NITER=20


# V3:
# gcc -O3 -fno-tree-vectorize src/main.c src/main.h src/gpucb3.h src/gpucb3.c


# Baseline:
gcc -O3 -fno-tree-vectorize src/main.c src/main.h src/gpucb.h src/gpucb.c


./a.out $NITER

python3 reference_gpucb.py $NITER
python3 tester.py
# python3 plot2.py
