#!/bin/bash

gcc -Wall -O3 -fno-tree-vectorize -I/usr/local/include -c main.c -o main.o
gcc -O3 -fno-tree-vectorize -L/usr/local/lib -lgsl -lgslcblas main.o
./a.out

python3 reference_gpucb.py
python3 tester.py
python3 plot.py
