#!/bin/bash

gcc -Wall -O3 -fno-tree-vectorize -march=skylake -I/usr/local/include -c cholesky.c -o cholesky.o
gcc -O3 -fno-tree-vectorize -march=core-avx2 -L/usr/local/lib -lgsl -lgslcblas cholesky.o
./a.out